"""
Pydantic models mirroring the Supabase schema.
Each model maps 1:1 to a table. Field names match column names exactly.
"""

from __future__ import annotations
from datetime import datetime
from typing import Optional
from pydantic import BaseModel, field_validator


# ---------------------------------------------------------------------------
# Agency — the municipality / public body that posted the job
# ---------------------------------------------------------------------------
class Agency(BaseModel):
    id: Optional[str] = None          # UUID, generated by Supabase
    name: str
    type: Optional[str] = None        # e.g. "city", "county", "district"
    website: Optional[str] = None
    contact_email: Optional[str] = None
    contact_phone: Optional[str] = None
    location_city: Optional[str] = None
    location_state: Optional[str] = None
    external_portal_id: Optional[str] = None   # PlanetBids portal ID e.g. "17950"
    scrape_log_id: Optional[str] = None


# ---------------------------------------------------------------------------
# Source — the platform we scraped from (e.g. PlanetBids portal 17950)
# ---------------------------------------------------------------------------
class Source(BaseModel):
    id: Optional[str] = None
    name: str
    base_url: str
    scrape_frequency: Optional[str] = None
    last_scraped_at: Optional[datetime] = None
    is_active: bool = True
    auth_credentials_ref: Optional[str] = None


# ---------------------------------------------------------------------------
# Job — the bid opportunity posted by an agency
# (PlanetBids calls this a "bid"; we call it a "job")
# ---------------------------------------------------------------------------
class Job(BaseModel):
    id: Optional[str] = None
    job_owner: Optional[str] = None       # FK → agencies.id
    title: str
    description: Optional[str] = None
    scope_of_work: Optional[str] = None
    trade_category: Optional[str] = None
    project_type: Optional[str] = None    # e.g. "construction", "services"
    estimated_value: Optional[float] = None
    posted_date: Optional[datetime] = None
    bid_due_date: Optional[datetime] = None
    project_start_date: Optional[datetime] = None
    location_city: Optional[str] = None
    location_state: Optional[str] = None
    location_lat: Optional[float] = None
    location_lng: Optional[float] = None
    status: Optional[str] = None          # "open" | "closed" | "awarded" | "cancelled"
    source_url: Optional[str] = None
    source_platform: Optional[str] = None # "planetbids"
    invitation_num: Optional[str] = None  # PlanetBids invitation/bid number
    bid_type: Optional[str] = None        # "RFP" | "RFQ" | "Bid" | "RFI" etc.
    category_codes: Optional[str] = None  # comma-separated e.g. "70000, 96500"
    last_modified: Optional[datetime] = None
    scrape_log_id: Optional[str] = None

    @field_validator("status", mode="before")
    @classmethod
    def normalize_status(cls, v: str | None) -> str | None:
        if not v:
            return None
        mapping = {
            "bidding": "open",
            "open": "open",
            "closed": "closed",
            "awarded": "awarded",
            "cancelled": "cancelled",
            "canceled": "cancelled",
        }
        return mapping.get(v.lower(), v.lower())

    @field_validator("estimated_value", mode="before")
    @classmethod
    def parse_currency(cls, v):
        if not v:
            return None
        if isinstance(v, str):
            cleaned = v.replace("$", "").replace(",", "").strip()
            return float(cleaned) if cleaned else None
        return v


# ---------------------------------------------------------------------------
# JobDetails — extended fields for a job (contact, bonds, pre-bid meeting)
# ---------------------------------------------------------------------------
class JobDetails(BaseModel):
    id: Optional[str] = None
    job_id: str                                    # FK → jobs.id
    agency_contact_name: Optional[str] = None
    agency_contact_email: Optional[str] = None
    agency_contact_phone: Optional[str] = None
    prebid_meeting_required: Optional[bool] = None
    prebid_meeting_date: Optional[datetime] = None
    prebid_meeting_location: Optional[str] = None
    bond_required: Optional[bool] = None
    bond_pct: Optional[float] = None
    liquidated_damages_per_day: Optional[float] = None
    addenda_count: Optional[int] = None
    bid_platform: Optional[str] = None            # "planetbids"
    bid_submission_method: Optional[str] = None
    prevailing_wage_required: Optional[bool] = None
    parsed_fields_json: Optional[dict] = None     # catch-all for extra fields
    scraped_at: Optional[datetime] = None
    last_modified: Optional[datetime] = None
    scrape_log_id: Optional[str] = None


# ---------------------------------------------------------------------------
# JobLineItem — individual line items within a job posting
# ---------------------------------------------------------------------------
class JobLineItem(BaseModel):
    id: Optional[str] = None
    job_id: str
    item_number: Optional[str] = None
    item_code: Optional[str] = None
    description: Optional[str] = None
    quantity: Optional[float] = None
    unit_of_measure: Optional[str] = None
    agency_unit_price: Optional[float] = None
    agency_item_total: Optional[float] = None
    section: Optional[str] = None
    scrape_log_id: Optional[str] = None


# ---------------------------------------------------------------------------
# JobMedia — documents / attachments for a job
# ---------------------------------------------------------------------------
class JobMedia(BaseModel):
    id: Optional[str] = None
    job_id: str
    file_name: Optional[str] = None
    file_url: Optional[str] = None
    file_type: Optional[str] = None
    uploaded_at: Optional[datetime] = None
    scrape_log_id: Optional[str] = None


# ---------------------------------------------------------------------------
# Company — a contractor / vendor / prospective bidder
# ---------------------------------------------------------------------------
class Company(BaseModel):
    id: Optional[str] = None
    name: str
    type: Optional[str] = None
    website: Optional[str] = None
    license_number: Optional[str] = None
    location_city: Optional[str] = None
    location_state: Optional[str] = None
    location_lat: Optional[float] = None
    location_lng: Optional[float] = None
    phone: Optional[str] = None
    email: Optional[str] = None
    legal_name: Optional[str] = None
    dba_name: Optional[str] = None
    scrape_log_id: Optional[str] = None


# ---------------------------------------------------------------------------
# Bid — a company's submission on a job (from prospective bidders list)
# ---------------------------------------------------------------------------
class Bid(BaseModel):
    id: Optional[str] = None
    job_id: str                                    # FK → jobs.id
    company_id: str                                # FK → companies.id
    contact_name: Optional[str] = None
    contact_email: Optional[str] = None
    contact_title: Optional[str] = None
    bidder_external_id: Optional[str] = None      # PlanetBids vendorId
    total_bid_amount: Optional[float] = None
    rank: Optional[int] = None
    working_days_bid: Optional[int] = None
    submitted_date: Optional[datetime] = None
    pct_subcontracted: Optional[float] = None
    subcontracted_dollar_amount: Optional[float] = None
    source: Optional[str] = None
    source_url: Optional[str] = None
    last_modified: Optional[datetime] = None
    scrape_log_id: Optional[str] = None


# ---------------------------------------------------------------------------
# Award — a bid that won (links job → winning company)
# ---------------------------------------------------------------------------
class Award(BaseModel):
    id: Optional[str] = None
    job_id: str                          # FK → jobs.id
    bid_id: Optional[str] = None        # FK → bids.id (if we have the submission)
    company_id: Optional[str] = None    # FK → companies.id
    awarded_amount: Optional[float] = None
    awarded_date: Optional[datetime] = None
    contract_number: Optional[str] = None
    status: Optional[str] = None
    scrape_log_id: Optional[str] = None


# ---------------------------------------------------------------------------
# ScrapeLog — one row per scraper run
# ---------------------------------------------------------------------------
class ScrapeLog(BaseModel):
    id: Optional[str] = None
    source_id: Optional[str] = None
    started_at: Optional[datetime] = None
    completed_at: Optional[datetime] = None
    jobs_found: int = 0
    jobs_new: int = 0
    jobs_updated: int = 0
    bids_new: int = 0
    companies_new: int = 0
    subcontractors_new: int = 0
    awards_new: int = 0
    contacts_new: int = 0
    errors_json: Optional[dict] = None
    status: str = "running"             # "running" | "complete" | "failed"